export const AGENT_REGISTRY = [
  {
    id: "orchestrator",
    name: "Central Orchestrator",
    description: "Interprets user prompts, breaks tasks into subtasks, assigns work to agents, and supervises the entire system.",
    category: "software",
    status: "idle",
    capabilities: ["task decomposition", "agent coordination", "output synthesis", "workflow management"],
    icon: "🧠",
    color: "violet",
  },
  {
    id: "software-architect",
    name: "Software Architect",
    description: "Designs application architecture, chooses frameworks, designs microservices and database schemas.",
    category: "software",
    status: "idle",
    capabilities: ["architecture design", "framework selection", "microservices", "API design", "schema design"],
    icon: "🏗️",
    color: "blue",
  },
  {
    id: "code-generator",
    name: "Code Generator",
    description: "Writes application code in Python, JavaScript, TypeScript, Go, Rust, Java, PHP and more.",
    category: "software",
    status: "idle",
    capabilities: ["Python", "JavaScript", "TypeScript", "Go", "Rust", "React", "Next.js", "Vue", "FastAPI", "Django"],
    icon: "💻",
    color: "green",
  },
  {
    id: "code-repair",
    name: "Auto Code Repair",
    description: "Runs continuously to detect bugs, automatically repair code, refactor inefficient logic, and optimize performance.",
    category: "software",
    status: "idle",
    capabilities: ["bug detection", "auto repair", "refactoring", "performance optimization"],
    icon: "🔧",
    color: "orange",
  },
  {
    id: "testing-agent",
    name: "Testing Agent",
    description: "Runs automated testing including unit tests, integration tests, UI tests, and performance tests.",
    category: "software",
    status: "idle",
    capabilities: ["unit testing", "integration testing", "UI testing", "performance testing"],
    icon: "🧪",
    color: "teal",
  },
  {
    id: "devops",
    name: "DevOps Agent",
    description: "Handles deployment and infrastructure with Docker, Kubernetes, Nginx. Sets up CI/CD pipelines and monitoring.",
    category: "devops",
    status: "idle",
    capabilities: ["Docker", "Kubernetes", "Nginx", "CI/CD", "monitoring", "server setup"],
    icon: "⚙️",
    color: "gray",
  },
  {
    id: "ui-ux",
    name: "UI/UX Design Agent",
    description: "Generates interfaces including SaaS dashboards, landing pages, mobile UI, and admin panels using Tailwind CSS.",
    category: "design",
    status: "idle",
    capabilities: ["SaaS dashboards", "landing pages", "mobile UI", "admin panels", "Tailwind CSS"],
    icon: "🎨",
    color: "pink",
  },
  {
    id: "security",
    name: "Security Agent",
    description: "Ensures system security with vulnerability scanning, authentication systems, secure APIs, and encryption.",
    category: "security",
    status: "idle",
    capabilities: ["vulnerability scanning", "OAuth", "JWT", "RBAC", "encryption", "secure APIs"],
    icon: "🔐",
    color: "red",
  },
  {
    id: "ai-integration",
    name: "AI Integration Agent",
    description: "Handles AI features including chatbots, automation systems, recommendation engines, and AI assistants.",
    category: "software",
    status: "idle",
    capabilities: ["chatbots", "automation", "recommendation engines", "LLM integration", "local LLMs"],
    icon: "🤖",
    color: "purple",
  },
  {
    id: "database",
    name: "Database Agent",
    description: "Manages PostgreSQL, MongoDB, Redis, SQLite databases with schema generation, indexing, and optimization.",
    category: "database",
    status: "idle",
    capabilities: ["PostgreSQL", "MongoDB", "Redis", "SQLite", "schema design", "indexing", "optimization"],
    icon: "🗄️",
    color: "yellow",
  },
  {
    id: "game-designer",
    name: "Game Designer Agent",
    description: "Creates game concepts including story design, gameplay mechanics, character systems, and game progression.",
    category: "game_studio",
    status: "idle",
    capabilities: ["story design", "gameplay mechanics", "character systems", "game progression", "level design"],
    icon: "🎮",
    color: "cyan",
  },
  {
    id: "game-engine",
    name: "Game Engine Agent",
    description: "Builds game projects in Godot, Unity, and Unreal Engine. Configures physics, generates scenes and scripts.",
    category: "game_studio",
    status: "idle",
    capabilities: ["Godot Engine", "Unity", "Unreal Engine", "physics", "scene generation", "GDScript"],
    icon: "🕹️",
    color: "green",
  },
  {
    id: "asset-generator",
    name: "Asset Generator",
    description: "Automatically generates 3D models, textures, sprites, animations, and UI elements for games.",
    category: "game_studio",
    status: "idle",
    capabilities: ["3D models", "textures", "sprites", "animations", "UI elements", "procedural generation"],
    icon: "🖼️",
    color: "indigo",
  },
  {
    id: "level-builder",
    name: "Level Builder Agent",
    description: "Generates game levels with map layouts, environment design, enemy placement, and puzzles.",
    category: "game_studio",
    status: "idle",
    capabilities: ["map layouts", "environment design", "enemy placement", "puzzles", "open world generation"],
    icon: "🗺️",
    color: "amber",
  },
  {
    id: "game-physics",
    name: "Game Physics Agent",
    description: "Handles physics simulation including collision detection, gravity, ragdoll physics, and vehicle physics.",
    category: "game_studio",
    status: "idle",
    capabilities: ["collision detection", "gravity systems", "ragdoll physics", "vehicle physics"],
    icon: "⚡",
    color: "yellow",
  },
  {
    id: "multiplayer",
    name: "Multiplayer Network Agent",
    description: "Creates multiplayer systems with matchmaking, real-time synchronization, and multiplayer servers.",
    category: "game_studio",
    status: "idle",
    capabilities: ["matchmaking", "real-time sync", "multiplayer servers", "WebSocket", "netcode"],
    icon: "🌐",
    color: "blue",
  },
  {
    id: "game-testing",
    name: "Game Testing Agent",
    description: "Automatically plays the game to detect bugs, find broken levels, and test performance.",
    category: "game_studio",
    status: "idle",
    capabilities: ["automated gameplay", "bug detection", "level testing", "performance testing"],
    icon: "🎯",
    color: "red",
  },
  {
    id: "startup-builder",
    name: "AI Startup Builder",
    description: "Builds SaaS businesses automatically by finding profitable niches, generating ideas, building and deploying products.",
    category: "business",
    status: "idle",
    capabilities: ["niche analysis", "SaaS idea generation", "business building", "auto-deployment"],
    icon: "🚀",
    color: "orange",
  },
  {
    id: "marketing",
    name: "AI Marketing Agent",
    description: "Promotes products automatically with ad generation, SEO content, social media posts, and marketing funnels.",
    category: "business",
    status: "idle",
    capabilities: ["ad generation", "SEO content", "social media", "marketing funnels", "copywriting"],
    icon: "📢",
    color: "pink",
  },
  {
    id: "sales",
    name: "AI Sales Agent",
    description: "Handles monetization with lead generation, email outreach, and onboarding funnels.",
    category: "business",
    status: "idle",
    capabilities: ["lead generation", "email outreach", "onboarding funnels", "CRM integration"],
    icon: "💰",
    color: "green",
  },
  {
    id: "analytics",
    name: "Analytics Agent",
    description: "Tracks platform performance with revenue tracking, product analytics, and growth metrics.",
    category: "business",
    status: "idle",
    capabilities: ["revenue tracking", "product analytics", "growth metrics", "A/B testing", "reporting"],
    icon: "📊",
    color: "blue",
  },

  // ── HYDRA-PRIME SWARM v4 agents — assignable via Command Center ─────────
  {
    id: "swarm-sovereign",
    name: "SOVEREIGN (CEO Architect)",
    description: "Layer 1 of HYDRA-PRIME SWARM v4. Reads the user prompt and outputs the master JSON blueprint: project type, stack, key features, complexity, and risks.",
    category: "hydra_swarm",
    status: "idle",
    capabilities: ["blueprint generation", "project decomposition", "risk analysis", "stack selection"],
    icon: "👑",
    color: "yellow",
  },
  {
    id: "swarm-architect",
    name: "Architect Council (×5)",
    description: "Layer 2. Five parallel specialists — System, UX, Data, Security, DevOps — each produce their section of the Technical Design Document.",
    category: "hydra_swarm",
    status: "idle",
    capabilities: ["system design", "UX design", "data architecture", "security architecture", "devops architecture"],
    icon: "🏛️",
    color: "blue",
  },
  {
    id: "swarm-dept-head",
    name: "Department Heads (×12)",
    description: "Layer 3. Up to 12 parallel department heads (Frontend, Backend, Database, Auth, Payments, AIML, DevOps, QA, Docs, GameEngine, MobileIOS, MobileAndroid) each decompose their domain into 5–10 atomic worker tasks.",
    category: "hydra_swarm",
    status: "idle",
    capabilities: ["task decomposition", "frontend", "backend", "database", "auth", "payments", "AIML", "devops"],
    icon: "🏢",
    color: "indigo",
  },
  {
    id: "swarm-worker",
    name: "Fractal Workers",
    description: "Layer 4. Every atomic task runs in parallel (pLimit capped). Oversized tasks auto-split into sub-swarms recursively. Each worker uses the SharedMemory blackboard (contextSnippet) for awareness of sibling work.",
    category: "hydra_swarm",
    status: "idle",
    capabilities: ["code generation", "fractal splitting", "parallel execution", "file emission"],
    icon: "⚙️",
    color: "green",
  },
  {
    id: "swarm-bug-hunter",
    name: "BugHunter Critic",
    description: "Layer 5 (Critic Ring). Adversarial bug-hunter that reviews generated artifacts for logic errors, race conditions, and null-dereference issues.",
    category: "hydra_swarm",
    status: "idle",
    capabilities: ["bug detection", "logic errors", "race conditions", "null safety"],
    icon: "🐛",
    color: "red",
  },
  {
    id: "swarm-security-auditor",
    name: "SecurityAuditor Critic",
    description: "Layer 5 (Critic Ring). Security auditor that finds injection vulnerabilities, auth bypasses, secret leaks, and OWASP issues in generated code.",
    category: "hydra_swarm",
    status: "idle",
    capabilities: ["injection detection", "auth bypass", "secret leaks", "OWASP", "vulnerability scanning"],
    icon: "🔍",
    color: "orange",
  },
  {
    id: "swarm-ux-critic",
    name: "UXCritic",
    description: "Layer 5 (Critic Ring). UX critic that finds poor user flows, missing loading/error/empty states, and accessibility issues in generated UI.",
    category: "hydra_swarm",
    status: "idle",
    capabilities: ["UX review", "flow analysis", "accessibility", "empty states", "error states"],
    icon: "🎨",
    color: "pink",
  },
  {
    id: "swarm-synthesizer",
    name: "SYNTHESIZER",
    description: "Layer 6. A long-context model that merges all agent-generated files into one complete, self-contained HTML file with full NEXUS_API integration and conflict resolution.",
    category: "hydra_swarm",
    status: "idle",
    capabilities: ["multi-file synthesis", "conflict resolution", "HTML generation", "NEXUS_API integration"],
    icon: "🧬",
    color: "cyan",
  },
  {
    id: "swarm-packager",
    name: "VALIDATOR & PACKAGER",
    description: "Layer 7. Final quality gate: cross-checks every blueprint feature against the synthesized HTML, fixes missing flows, polishes UI states, and returns the production-ready output.",
    category: "hydra_swarm",
    status: "idle",
    capabilities: ["feature validation", "quality assurance", "UI polish", "blueprint cross-check"],
    icon: "📦",
    color: "violet",
  },
];
