import { ReplitConnectors } from "@replit/connectors-sdk";

const EXPO_OWNER   = "Nexuselitestudio";
const GITHUB_OWNER = "bosslifeempire777-art";

const connectors = new ReplitConnectors();

async function gh(endpoint: string, options: RequestInit = {}): Promise<any> {
  const res = await connectors.proxy("github", endpoint, options);
  const text = await res.text();
  if (!res.ok) throw new Error(`GitHub ${res.status} on ${endpoint}: ${text.slice(0, 300)}`);
  try { return JSON.parse(text); } catch { return text; }
}

async function ghPut(endpoint: string, body: unknown): Promise<any> {
  return gh(endpoint, {
    method: "PUT",
    body: JSON.stringify(body),
    headers: { "Content-Type": "application/json" },
  });
}

async function easApi(path: string, options: RequestInit = {}): Promise<any> {
  const token = process.env.EXPO_TOKEN;
  if (!token) throw new Error("EXPO_TOKEN not set");
  const res = await fetch(`https://api.expo.dev${path}`, {
    ...options,
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
      ...(options.headers ?? {}),
    },
  });
  const text = await res.text();
  if (!res.ok) throw new Error(`EAS ${res.status} on ${path}: ${text.slice(0, 300)}`);
  try { return JSON.parse(text); } catch { return text; }
}

export interface ExpoProjectFiles {
  name: string;
  slug: string;
  files: Record<string, string>;
}

export interface MobileBuildResult {
  buildId:    string;
  status:     "in-queue" | "in-progress" | "finished" | "errored" | "cancelled" | "new";
  platform:   "android" | "ios";
  artifactUrl: string | null;
  expiresAt:  string | null;
  repoUrl:    string | null;
  error:      string | null;
}

export interface MobileBuildStatus {
  buildId:     string;
  status:      string;
  platform:    string;
  artifactUrl: string | null;
  expiresAt:   string | null;
  error:       string | null;
  logsUrl:     string | null;
}

async function ensureGitHubRepo(repoName: string): Promise<void> {
  try {
    await gh(`/repos/${GITHUB_OWNER}/${repoName}`);
    console.log(`[EAS] GitHub repo ${GITHUB_OWNER}/${repoName} already exists`);
  } catch {
    console.log(`[EAS] Creating GitHub repo ${repoName}...`);
    await gh("/user/repos", {
      method: "POST",
      body: JSON.stringify({
        name: repoName,
        private: true,
        auto_init: true,
        description: "Generated by NexusElite AI Studio",
      }),
      headers: { "Content-Type": "application/json" },
    });
    await new Promise(r => setTimeout(r, 2000));
  }
}

async function getRepoDefaultBranch(repoName: string): Promise<string> {
  const data = await gh(`/repos/${GITHUB_OWNER}/${repoName}`);
  return data.default_branch ?? "main";
}

async function getLatestCommitSha(repoName: string, branch: string): Promise<string> {
  const data = await gh(`/repos/${GITHUB_OWNER}/${repoName}/git/ref/heads/${branch}`);
  return data.object.sha;
}

async function getTreeSha(repoName: string, commitSha: string): Promise<string> {
  const data = await gh(`/repos/${GITHUB_OWNER}/${repoName}/git/commits/${commitSha}`);
  return data.tree.sha;
}

async function pushFilesToGitHub(repoName: string, files: Record<string, string>): Promise<string> {
  await ensureGitHubRepo(repoName);
  const branch    = await getRepoDefaultBranch(repoName);
  const commitSha = await getLatestCommitSha(repoName, branch);
  const treeSha   = await getTreeSha(repoName, commitSha);

  const treeItems = Object.entries(files).map(([path, content]) => ({
    path,
    mode: "100644",
    type: "blob",
    content,
  }));

  const newTree = await gh(`/repos/${GITHUB_OWNER}/${repoName}/git/trees`, {
    method: "POST",
    body: JSON.stringify({ base_tree: treeSha, tree: treeItems }),
    headers: { "Content-Type": "application/json" },
  });

  const newCommit = await gh(`/repos/${GITHUB_OWNER}/${repoName}/git/commits`, {
    method: "POST",
    body: JSON.stringify({
      message: "Generated by NexusElite AI Studio",
      tree: newTree.sha,
      parents: [commitSha],
    }),
    headers: { "Content-Type": "application/json" },
  });

  await ghPut(`/repos/${GITHUB_OWNER}/${repoName}/git/refs/heads/${branch}`, {
    sha: newCommit.sha,
    force: true,
  });

  console.log(`[EAS] Pushed ${Object.keys(files).length} files to ${GITHUB_OWNER}/${repoName}`);
  return `https://github.com/${GITHUB_OWNER}/${repoName}`;
}

async function ensureEasProject(slug: string): Promise<string> {
  try {
    const data = await easApi(`/v2/projects?slug=${encodeURIComponent(slug)}&owner=${EXPO_OWNER}`);
    const projects = data?.data ?? [];
    if (projects.length > 0) {
      console.log(`[EAS] Project ${slug} already exists: ${projects[0].id}`);
      return projects[0].id;
    }
  } catch { /* not found */ }

  console.log(`[EAS] Creating EAS project ${slug}...`);
  const data = await easApi("/v2/projects", {
    method: "POST",
    body: JSON.stringify({ slug, name: slug, owner: EXPO_OWNER }),
  });
  return data.data?.id ?? data.id;
}

export async function triggerMobileBuild(opts: {
  projectId:    string;
  projectName:  string;
  platform:     "android" | "ios";
  files:        Record<string, string>;
}): Promise<MobileBuildResult> {
  const { projectId, projectName, platform, files } = opts;

  const repoSlug  = `nexus-mobile-${projectId}`.slice(0, 60);
  const easSlug   = `nexus-${projectId}`.slice(0, 50).toLowerCase().replace(/[^a-z0-9-]/g, "-");

  const repoUrl = await pushFilesToGitHub(repoSlug, files);
  await ensureEasProject(easSlug);

  console.log(`[EAS] Triggering ${platform} build for ${projectName}...`);
  const buildData = await easApi("/v2/builds", {
    method: "POST",
    body: JSON.stringify({
      appId:    easSlug,
      owner:    EXPO_OWNER,
      platform,
      channel:  "production",
      buildProfile: "preview",
      autoSubmit: false,
      metadata: {
        appName:    projectName,
        appVersion: "1.0.0",
        username:   EXPO_OWNER,
      },
    }),
  });

  const build = buildData?.data ?? buildData;
  return {
    buildId:     build.id ?? build.buildId ?? "unknown",
    status:      build.status ?? "in-queue",
    platform,
    artifactUrl: build.artifacts?.applicationArchiveUrl ?? null,
    expiresAt:   build.expirationDate ?? null,
    repoUrl,
    error:       null,
  };
}

export async function getMobileBuildStatus(buildId: string): Promise<MobileBuildStatus> {
  const data = await easApi(`/v2/builds/${buildId}`);
  const build = data?.data ?? data;
  return {
    buildId,
    status:      build.status ?? "unknown",
    platform:    build.platform ?? "android",
    artifactUrl: build.artifacts?.applicationArchiveUrl ?? null,
    expiresAt:   build.expirationDate ?? null,
    error:       build.error?.message ?? null,
    logsUrl:     build.logsPageUrl ?? `https://expo.dev/accounts/${EXPO_OWNER}/projects/builds/${buildId}`,
  };
}
