import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { mkdtemp, writeFile, mkdir } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, dirname, resolve } from "node:path";

const execFileAsync = promisify(execFile);

const EXPO_OWNER   = "Nexuselitestudio";
const GITHUB_OWNER = "bosslifeempire777-art";

// process.cwd() is the workspace root in both dev (pnpm --filter) and prod
// (node artifacts/api-server/dist/index.cjs run from workspace root)
const EAS_BIN = resolve(process.cwd(), "artifacts/api-server/node_modules/.bin/eas");

export interface MobileBuildResult {
  buildId:     string;
  status:      string;
  platform:    "android" | "ios";
  artifactUrl: string | null;
  expiresAt:   string | null;
  repoUrl:     string | null;
  error:       string | null;
  logsUrl:     string | null;
}

export interface MobileBuildStatus {
  buildId:     string;
  status:      string;
  platform:    string;
  artifactUrl: string | null;
  expiresAt:   string | null;
  error:       string | null;
  logsUrl:     string | null;
}

async function writeTempProject(files: Record<string, string>): Promise<string> {
  const dir = await mkdtemp(join(tmpdir(), "nexus-build-"));
  for (const [filePath, content] of Object.entries(files)) {
    const full = join(dir, filePath);
    await mkdir(dirname(full), { recursive: true });
    await writeFile(full, content, "utf8");
  }
  console.log(`[EAS] Wrote ${Object.keys(files).length} files to ${dir}`);
  return dir;
}

async function runEasCli(
  args: string[],
  cwd: string,
  timeoutMs = 300_000,
): Promise<string> {
  const token = process.env.EXPO_TOKEN;
  if (!token) throw new Error("EXPO_TOKEN not set");

  console.log(`[EAS] Running: eas ${args.join(" ")} (cwd=${cwd})`);
  const { stdout, stderr } = await execFileAsync(EAS_BIN, args, {
    cwd,
    timeout: timeoutMs,
    env: {
      ...process.env,
      EXPO_TOKEN: token,
      CI: "1",
      EXPO_NO_TELEMETRY: "1",
    },
  });
  if (stderr) console.log(`[EAS stderr] ${stderr.slice(0, 500)}`);
  return stdout;
}

async function pushFilesToGitHub(
  repoName: string,
  files: Record<string, string>,
): Promise<string> {
  try {
    const { ReplitConnectors } = await import("@replit/connectors-sdk");
    const connectors = new ReplitConnectors();

    async function gh(endpoint: string, options: RequestInit = {}): Promise<any> {
      const res = await connectors.proxy("github", endpoint, options);
      const text = await res.text();
      if (!res.ok) throw new Error(`GitHub ${res.status} on ${endpoint}: ${text.slice(0, 300)}`);
      try { return JSON.parse(text); } catch { return text; }
    }

    try {
      await gh(`/repos/${GITHUB_OWNER}/${repoName}`);
    } catch {
      await gh("/user/repos", {
        method: "POST",
        body: JSON.stringify({ name: repoName, private: true, auto_init: true, description: "Generated by NexusElite AI Studio" }),
        headers: { "Content-Type": "application/json" },
      });
      await new Promise(r => setTimeout(r, 2500));
    }

    const repoData  = await gh(`/repos/${GITHUB_OWNER}/${repoName}`);
    const branch    = repoData.default_branch ?? "main";
    const refData   = await gh(`/repos/${GITHUB_OWNER}/${repoName}/git/ref/heads/${branch}`);
    const commitSha = refData.object.sha;
    const commitData = await gh(`/repos/${GITHUB_OWNER}/${repoName}/git/commits/${commitSha}`);
    const treeSha   = commitData.tree.sha;

    const newTree = await gh(`/repos/${GITHUB_OWNER}/${repoName}/git/trees`, {
      method: "POST",
      body: JSON.stringify({
        base_tree: treeSha,
        tree: Object.entries(files).map(([path, content]) => ({ path, mode: "100644", type: "blob", content })),
      }),
      headers: { "Content-Type": "application/json" },
    });

    const newCommit = await gh(`/repos/${GITHUB_OWNER}/${repoName}/git/commits`, {
      method: "POST",
      body: JSON.stringify({ message: "Generated by NexusElite AI Studio", tree: newTree.sha, parents: [commitSha] }),
      headers: { "Content-Type": "application/json" },
    });

    await gh(`/repos/${GITHUB_OWNER}/${repoName}/git/refs/heads/${branch}`, {
      method: "PATCH",
      body: JSON.stringify({ sha: newCommit.sha, force: true }),
      headers: { "Content-Type": "application/json" },
    });

    console.log(`[EAS] Pushed ${Object.keys(files).length} files to GitHub: ${GITHUB_OWNER}/${repoName}`);
    return `https://github.com/${GITHUB_OWNER}/${repoName}`;
  } catch (err) {
    console.warn(`[EAS] GitHub push failed (non-fatal): ${err}`);
    return "";
  }
}

export async function triggerMobileBuild(opts: {
  projectId:   string;
  projectName: string;
  platform:    "android" | "ios" | "all";
  files:       Record<string, string>;
}): Promise<MobileBuildResult[]> {
  const { projectId, projectName, platform, files } = opts;
  const repoSlug = `nexus-mobile-${projectId}`.slice(0, 60);

  const [dir, repoUrl] = await Promise.all([
    writeTempProject(files),
    pushFilesToGitHub(repoSlug, files),
  ]);

  console.log(`[EAS] Triggering ${platform} EAS build for "${projectName}"…`);

  const output = await runEasCli(
    [
      "build",
      "--platform", platform,
      "--profile", "preview",
      "--non-interactive",
      "--no-wait",
      "--json",
    ],
    dir,
  );

  let builds: any[] = [];
  try {
    const parsed = JSON.parse(output.trim());
    builds = Array.isArray(parsed) ? parsed : [parsed];
  } catch {
    const idMatch = output.match(/"id"\s*:\s*"([^"]+)"/);
    builds = [{ id: idMatch?.[1] ?? "unknown", status: "in-queue", platform: platform === "all" ? "android" : platform }];
  }

  return builds.map((build: any) => {
    const buildId = build.id ?? build.buildId ?? "unknown";
    const resolvedPlatform: "android" | "ios" =
      String(build.platform ?? "").toLowerCase().includes("ios") ? "ios" : "android";
    console.log(`[EAS] Build queued: ${buildId} (${resolvedPlatform})`);
    return {
      buildId,
      status:      build.status ?? "in-queue",
      platform:    resolvedPlatform,
      artifactUrl: build.artifacts?.applicationArchiveUrl ?? null,
      expiresAt:   build.expirationDate ?? null,
      repoUrl:     repoUrl || null,
      error:       null,
      logsUrl:     `https://expo.dev/accounts/${EXPO_OWNER}/projects/builds/${buildId}`,
    };
  });
}

export async function getMobileBuildStatus(buildId: string): Promise<MobileBuildStatus> {
  const token = process.env.EXPO_TOKEN;
  if (!token) throw new Error("EXPO_TOKEN not set");

  const res = await fetch(`https://api.expo.dev/v2/builds/${buildId}`, {
    headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
  });
  const text = await res.text();
  if (!res.ok) throw new Error(`EAS status ${res.status}: ${text.slice(0, 300)}`);

  const data  = JSON.parse(text);
  const build = data?.data ?? data;

  return {
    buildId,
    status:      build.status ?? "unknown",
    platform:    build.platform?.toLowerCase() ?? "android",
    artifactUrl: build.artifacts?.applicationArchiveUrl ?? null,
    expiresAt:   build.expirationDate ?? null,
    error:       build.error?.message ?? null,
    logsUrl:     build.logsPageUrl ?? `https://expo.dev/accounts/${EXPO_OWNER}/projects/builds/${buildId}`,
  };
}
