import { callLLM } from "./openrouter.js";

export interface FlutterFiles {
  [path: string]: string;
}

const PUBSPEC_TEMPLATE = (name: string, slug: string) => `name: ${slug}
description: ${name} - generated by NexusElite AI Studio
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  go_router: ^13.0.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
`;

const ANALYSIS_OPTIONS = `include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
`;

const GITIGNORE = `# Miscellaneous
*.class
*.log
*.pyc
*.swp
.DS_Store
.atom/
.buildlog/
.history
.svn/
migrate_working_dir/

# IntelliJ related
*.iml
*.ipr
*.iws
.idea/

# VSCode related
.vscode/

# Flutter/Dart/Pub related
**/doc/api/
**/ios/Flutter/.last_build_id
.dart_tool/
.flutter-plugins
.flutter-plugins-dependencies
.pub-cache/
.pub/
/build/

# Symbolication related
app.*.symbols

# Obfuscation related
app.*.map.json

# Android Studio will place build artifacts here
/android/app/debug
/android/app/profile
/android/app/release
`;

const README_TEMPLATE = (name: string) => `# ${name}

Generated by **NexusElite AI Studio** using Flutter.

## Requirements

- [Flutter SDK](https://docs.flutter.dev/get-started/install) ≥ 3.10.0
- Android Studio / Xcode (for native builds)

## Getting Started

\`\`\`bash
# Install dependencies
flutter pub get

# Run on connected device or emulator
flutter run

# Build Android APK
flutter build apk --release

# Build iOS (macOS only)
flutter build ios --release

# Build for web
flutter build web
\`\`\`

## Cloud Build (no local SDK needed)

Use [Codemagic](https://codemagic.io/) or [Bitrise](https://www.bitrise.io/) for
CI/CD builds without a local Flutter installation.

---

*Built with NexusElite AI Studio*
`;

export async function generateFlutterCode(
  name: string,
  prompt: string,
  projectId: string,
): Promise<FlutterFiles> {
  const slug = name.toLowerCase().replace(/[^a-z0-9_]/g, "_").slice(0, 40) || "nexus_app";

  const system = `You are an expert Flutter/Dart developer who builds polished, production-ready mobile apps with clean architecture.

CRITICAL RULES:
1. Output ONLY a JSON object where each key is a file path and the value is the complete file content as a string.
2. No markdown, no code fences, no explanation — ONLY the raw JSON object.
3. The JSON must be parseable by JSON.parse().
4. Use proper Dart/Flutter syntax. All files must be valid Dart code.
5. Use Material Design 3 with a dark theme by default.
6. Use go_router for navigation between screens.
7. Use provider for state management.
8. Create at least 3-4 meaningful screens relevant to the app concept.
9. Add real, functional UI — not placeholder lorem ipsum text.
10. All widget classes must extend StatelessWidget or StatefulWidget correctly.

REQUIRED FILE STRUCTURE:
- lib/main.dart (entry point, MaterialApp.router with go_router, dark theme)
- lib/app/router.dart (GoRouter configuration with all routes)
- lib/app/theme.dart (ThemeData with dark Material 3 color scheme, neon accents)
- lib/screens/home_screen.dart (main home screen)
- lib/screens/ (2-3 additional feature screens relevant to the app)
- lib/widgets/custom_app_bar.dart (shared app bar widget)
- lib/widgets/bottom_nav.dart (bottom navigation bar if applicable)
- lib/models/ (1-2 data model classes if relevant)
- lib/providers/ (state provider class if needed)

DESIGN GUIDELINES:
- Dark background: #0A0A0F or similar deep dark
- Primary accent: vibrant purple/cyan gradient (#7C3AED / #00D4FF)
- Cards with rounded corners (16px), subtle borders
- Use GoogleFonts or system fonts for typography
- Smooth animations with AnimatedContainer where appropriate
- Bottom navigation with 3-4 tabs

The app name is "${name}" (package slug: "${slug}").
The app description/prompt is: "${prompt}"

Design a beautiful, feature-complete Flutter app that matches the prompt. Make it look like a real production app.`;

  const userMsg = `Generate the complete Flutter source code for "${name}".
App concept: ${prompt}
Output as a single JSON object with file paths as keys and complete file contents as values.`;

  let raw = "";
  try {
    raw = await callLLM(userMsg, {
      system,
      tier:        "reasoning",
      maxTokens:   8000,
      temperature: 0.4,
    });
  } catch {
    raw = await callLLM(userMsg, {
      system,
      tier:        "coding",
      maxTokens:   8000,
      temperature: 0.4,
    });
  }

  // Strip markdown fences if present
  let cleaned = raw.trim();
  if (cleaned.startsWith("```")) {
    cleaned = cleaned.replace(/^```[a-z]*\n?/, "").replace(/\n?```$/, "").trim();
  }

  let files: FlutterFiles = {};
  try {
    files = JSON.parse(cleaned);
  } catch {
    const jsonMatch = cleaned.match(/\{[\s\S]+\}/);
    if (jsonMatch) {
      try { files = JSON.parse(jsonMatch[0]); } catch { /* fallback below */ }
    }
  }

  // Always inject the scaffold files so the project is always buildable
  files["pubspec.yaml"]         = PUBSPEC_TEMPLATE(name, slug);
  files["analysis_options.yaml"] = ANALYSIS_OPTIONS;
  files[".gitignore"]           = GITIGNORE;
  files["README.md"]            = README_TEMPLATE(name);
  files["assets/images/.keep"]  = "";

  // Ensure lib/main.dart exists as a fallback
  if (!files["lib/main.dart"]) {
    files["lib/main.dart"] = `import 'package:flutter/material.dart';

void main() {
  runApp(const ${toClassName(name)}App());
}

class ${toClassName(name)}App extends StatelessWidget {
  const ${toClassName(name)}App({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: '${name}',
      debugShowCheckedModeBanner: false,
      theme: ThemeData.dark(useMaterial3: true).copyWith(
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF7C3AED),
          brightness: Brightness.dark,
        ),
      ),
      home: const HomeScreen(),
    );
  }
}

class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('${name}')),
      body: const Center(
        child: Text('Welcome to ${name}', style: TextStyle(fontSize: 24)),
      ),
    );
  }
}
`;
  }

  console.log(`[Flutter] Generated ${Object.keys(files).length} files for "${name}" (project ${projectId})`);
  return files;
}

function toClassName(name: string): string {
  return name
    .replace(/[^a-zA-Z0-9 ]/g, " ")
    .split(" ")
    .filter(Boolean)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
}
