import { pgTable, text, timestamp, uniqueIndex } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

/**
 * Per-user secret storage. Lets a user save their own API keys
 * (OpenAI, Stripe, SendGrid, etc.) so the apps generated by
 * Nexus Studio can use them at runtime.
 *
 * - `name`   = label / variable name the user picks (e.g. "OPENAI_API_KEY")
 * - `value`  = the actual secret value (stored as text)
 * - `category` = optional grouping label (e.g. "ai", "payments")
 * - `description` = optional note about what the key is for
 *
 * Values are NEVER returned in list endpoints — only masked previews.
 * The full value is only injected server-side into the user's own
 * generated app preview HTML; admins cannot see other users' values.
 */
export const userSecretsTable = pgTable(
  "user_secrets",
  {
    id: text("id").primaryKey(),
    userId: text("user_id").notNull(),
    name: text("name").notNull(),
    value: text("value").notNull(),
    category: text("category").notNull().default("general"),
    description: text("description"),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
  },
  (t) => ({
    userNameUq: uniqueIndex("user_secrets_user_name_uq").on(t.userId, t.name),
  }),
);

export const insertUserSecretSchema = createInsertSchema(userSecretsTable).omit({
  createdAt: true,
  updatedAt: true,
});
export type InsertUserSecret = z.infer<typeof insertUserSecretSchema>;
export type UserSecret = typeof userSecretsTable.$inferSelect;
