import { useState, useEffect, useRef } from "react";
import { Link } from "wouter";
import { Rocket, Zap } from "lucide-react";

const PROMPT = "Build me a SaaS dashboard for tracking ad campaigns with live analytics";

const AGENTS = [
  { name: "Orchestrator",    role: "Analyzing requirements...",    color: "text-primary",    bar: "bg-primary"    },
  { name: "Architect Agent", role: "Designing system structure...", color: "text-blue-400",   bar: "bg-blue-400"   },
  { name: "UI/UX Designer",  role: "Creating interface layout...", color: "text-purple-400", bar: "bg-purple-400" },
  { name: "Code Generator",  role: "Writing production code...",   color: "text-green-400",  bar: "bg-green-400"  },
  { name: "Database Agent",  role: "Modeling data schema...",      color: "text-yellow-400", bar: "bg-yellow-400" },
  { name: "Security Auditor",role: "Running security checks...",   color: "text-red-400",    bar: "bg-red-400"    },
  { name: "DevOps Agent",    role: "Preparing deployment...",      color: "text-accent",     bar: "bg-accent"     },
];

const CODE = [
  { text: "// AdTracker Pro — Generated by NexusElite", color: "text-muted-foreground" },
  { text: "const app = new SaaSDashboard({",            color: "text-foreground"       },
  { text: "  name: 'AdTracker Pro',",                   color: "text-green-400"        },
  { text: "  auth: { provider: 'JWT', mfa: true },",    color: "text-blue-400"         },
  { text: "  analytics: realtimeMetrics({ live: true }),", color: "text-yellow-400"    },
  { text: "  charts: ['revenue', 'ctr', 'conversions'],", color: "text-purple-400"     },
  { text: "  deploy: { cdn: true, ssl: true },",         color: "text-accent"           },
  { text: "});",                                          color: "text-foreground"       },
  { text: "",                                             color: ""                      },
  { text: "app.launch(); // ✅ Ready in 47 seconds",     color: "text-primary"          },
];

const PHASES = {
  IDLE:    0,
  TYPING:  1,
  AGENTS:  2,
  CODE:    3,
  PREVIEW: 4,
  DONE:    5,
};

export function HomeDemoPlayer() {
  const [phase, setPhase]           = useState(PHASES.IDLE);
  const [typedLen, setTypedLen]     = useState(0);
  const [agentCount, setAgentCount] = useState(0);
  const [codeCount, setCodeCount]   = useState(0);
  const [showPreview, setShowPreview] = useState(false);
  const [showBadge, setShowBadge]   = useState(false);
  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  function reset() {
    setPhase(PHASES.IDLE);
    setTypedLen(0);
    setAgentCount(0);
    setCodeCount(0);
    setShowPreview(false);
    setShowBadge(false);
  }

  useEffect(() => {
    const clear = () => { if (timerRef.current) clearTimeout(timerRef.current); };

    if (phase === PHASES.IDLE) {
      timerRef.current = setTimeout(() => setPhase(PHASES.TYPING), 800);
    }

    if (phase === PHASES.TYPING) {
      if (typedLen < PROMPT.length) {
        timerRef.current = setTimeout(() => setTypedLen(n => n + 1), 38);
      } else {
        timerRef.current = setTimeout(() => setPhase(PHASES.AGENTS), 600);
      }
    }

    if (phase === PHASES.AGENTS) {
      if (agentCount < AGENTS.length) {
        timerRef.current = setTimeout(() => setAgentCount(n => n + 1), 420);
      } else {
        timerRef.current = setTimeout(() => setPhase(PHASES.CODE), 500);
      }
    }

    if (phase === PHASES.CODE) {
      if (codeCount < CODE.length) {
        timerRef.current = setTimeout(() => setCodeCount(n => n + 1), 280);
      } else {
        timerRef.current = setTimeout(() => {
          setShowPreview(true);
          setPhase(PHASES.PREVIEW);
        }, 400);
      }
    }

    if (phase === PHASES.PREVIEW) {
      timerRef.current = setTimeout(() => {
        setShowBadge(true);
        setPhase(PHASES.DONE);
      }, 2200);
    }

    if (phase === PHASES.DONE) {
      timerRef.current = setTimeout(() => reset(), 3800);
    }

    return clear;
  }, [phase, typedLen, agentCount, codeCount]);

  const isActive = phase >= PHASES.TYPING;

  return (
    <section className="relative z-10 py-24 border-t border-border/50 overflow-hidden">
      {/* Background glow */}
      <div className="absolute inset-0 pointer-events-none">
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-primary/5 rounded-full blur-3xl" />
      </div>

      <div className="container mx-auto px-6">

        {/* Header */}
        <div className="text-center mb-12">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border border-primary/30 bg-primary/5 text-primary text-xs font-mono mb-4">
            <span className="w-2 h-2 rounded-full bg-primary animate-pulse" />
            WATCH THE SWARM BUILD IN REAL TIME
          </div>
          <h2 className="text-3xl md:text-4xl font-display font-bold text-glow mb-3">
            TYPE A PROMPT. GET A FULL APP.
          </h2>
          <p className="text-muted-foreground font-mono text-sm max-w-lg mx-auto">
            21 AI agents work in parallel — architect, design, code, secure, and deploy — all from a single sentence.
          </p>
        </div>

        {/* Demo Player */}
        <div className="max-w-5xl mx-auto">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-0 border border-border/60 rounded-lg overflow-hidden shadow-2xl shadow-primary/10">

            {/* LEFT PANEL — Prompt + Agent Swarm */}
            <div className="bg-card/80 border-r border-border/50 flex flex-col">
              {/* Window chrome */}
              <div className="flex items-center gap-1.5 px-4 py-3 border-b border-border/40 bg-secondary/30">
                <span className="w-3 h-3 rounded-full bg-red-500/60" />
                <span className="w-3 h-3 rounded-full bg-yellow-500/60" />
                <span className="w-3 h-3 rounded-full bg-green-500/60" />
                <span className="ml-3 text-xs font-mono text-muted-foreground">nexuselite — agent terminal</span>
              </div>

              {/* Prompt area */}
              <div className="p-4 border-b border-border/30">
                <div className="text-xs font-mono text-muted-foreground mb-2 uppercase tracking-wider">Your prompt:</div>
                <div className="bg-background/60 border border-primary/20 rounded px-3 py-2.5 min-h-[52px] font-mono text-sm text-foreground relative">
                  <span>{PROMPT.slice(0, typedLen)}</span>
                  {phase === PHASES.TYPING && (
                    <span className="inline-block w-0.5 h-4 bg-primary animate-pulse ml-0.5 align-middle" />
                  )}
                  {phase === PHASES.IDLE && (
                    <span className="text-muted-foreground/40">Describe your app idea...</span>
                  )}
                </div>
                {isActive && phase >= PHASES.AGENTS && (
                  <div className="mt-2 flex items-center gap-2">
                    <span className="w-1.5 h-1.5 rounded-full bg-primary animate-ping" />
                    <span className="text-xs font-mono text-primary">Swarm Engaged — {AGENTS.length} agents active</span>
                  </div>
                )}
              </div>

              {/* Agent list */}
              <div className="flex-1 p-4 space-y-2.5 overflow-hidden">
                <div className="text-xs font-mono text-muted-foreground uppercase tracking-wider mb-3">Agent Swarm:</div>
                {AGENTS.map((agent, i) => {
                  const active = i < agentCount;
                  const done   = phase >= PHASES.CODE && i < agentCount;
                  return (
                    <div
                      key={agent.name}
                      className={`transition-all duration-500 ${active ? "opacity-100 translate-x-0" : "opacity-0 -translate-x-4"}`}
                    >
                      <div className="flex items-center justify-between mb-1">
                        <div className="flex items-center gap-2">
                          <span className={`w-1.5 h-1.5 rounded-full ${done ? agent.bar : "bg-muted-foreground/30"} ${active && !done ? "animate-pulse" : ""}`} />
                          <span className={`text-xs font-mono font-bold ${active ? agent.color : "text-muted-foreground"}`}>
                            {agent.name}
                          </span>
                        </div>
                        <span className="text-xs font-mono text-muted-foreground/60">
                          {done ? "✓ Done" : active ? "Running" : ""}
                        </span>
                      </div>
                      {active && (
                        <div className="ml-3.5 h-1 bg-secondary rounded-full overflow-hidden">
                          <div
                            className={`h-full ${agent.bar} rounded-full transition-all duration-1000 ${done ? "w-full" : "w-3/4"}`}
                          />
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>

            {/* RIGHT PANEL — Code + Preview */}
            <div className="bg-[#0d0d1a] flex flex-col">
              {/* Window chrome */}
              <div className="flex items-center gap-1.5 px-4 py-3 border-b border-border/40 bg-secondary/20">
                <span className="w-3 h-3 rounded-full bg-red-500/60" />
                <span className="w-3 h-3 rounded-full bg-yellow-500/60" />
                <span className="w-3 h-3 rounded-full bg-green-500/60" />
                <span className="ml-3 text-xs font-mono text-muted-foreground">adtracker-pro.nexuselitestudio.nexus</span>
                {showBadge && (
                  <span className="ml-auto text-xs font-mono text-green-400 bg-green-400/10 border border-green-400/30 px-2 py-0.5 rounded-full animate-pulse">
                    ● LIVE
                  </span>
                )}
              </div>

              {/* Code editor (shows during code phase) */}
              {!showPreview && (
                <div className="flex-1 p-4 font-mono text-xs leading-relaxed overflow-hidden">
                  {phase < PHASES.CODE && (
                    <div className="text-muted-foreground/30 animate-pulse">Waiting for agents...</div>
                  )}
                  {CODE.slice(0, codeCount).map((line, i) => (
                    <div key={i} className={`${line.color} transition-all duration-300`}>
                      <span className="text-muted-foreground/30 mr-4 select-none">{String(i + 1).padStart(2, " ")}</span>
                      {line.text}
                    </div>
                  ))}
                  {phase === PHASES.CODE && codeCount < CODE.length && (
                    <div className="text-muted-foreground/30">
                      <span className="mr-4">{String(codeCount + 1).padStart(2, " ")}</span>
                      <span className="inline-block w-0.5 h-3 bg-primary animate-pulse align-middle" />
                    </div>
                  )}
                </div>
              )}

              {/* Live preview (shows during preview/done phases) */}
              {showPreview && (
                <div className="flex-1 overflow-hidden">
                  {/* Fake app preview */}
                  <div className="h-full bg-[#111827] p-3 flex flex-col gap-2 animate-[fadeIn_0.6s_ease]">
                    {/* Topbar */}
                    <div className="flex items-center justify-between bg-[#1f2937] rounded px-3 py-2">
                      <div className="flex items-center gap-2">
                        <div className="w-2 h-2 rounded-full bg-primary animate-pulse" />
                        <span className="text-xs font-mono text-white font-bold">AdTracker Pro</span>
                      </div>
                      <div className="flex gap-1">
                        {["Dashboard","Campaigns","Analytics","Settings"].map(t => (
                          <span key={t} className={`text-xs font-mono px-2 py-0.5 rounded ${t==="Dashboard" ? "bg-primary text-black" : "text-gray-400"}`}>{t}</span>
                        ))}
                      </div>
                    </div>
                    {/* KPI row */}
                    <div className="grid grid-cols-4 gap-2">
                      {[
                        { label: "Revenue",     value: "$48,291", color: "text-green-400", bg: "bg-green-400/10" },
                        { label: "CTR",          value: "3.82%",   color: "text-blue-400",  bg: "bg-blue-400/10"  },
                        { label: "Conversions",  value: "1,204",   color: "text-purple-400",bg: "bg-purple-400/10"},
                        { label: "ROAS",         value: "4.7x",    color: "text-yellow-400",bg: "bg-yellow-400/10"},
                      ].map(k => (
                        <div key={k.label} className={`${k.bg} rounded p-2 border border-white/5`}>
                          <div className={`text-sm font-mono font-bold ${k.color}`}>{k.value}</div>
                          <div className="text-xs text-gray-400 font-mono mt-0.5">{k.label}</div>
                        </div>
                      ))}
                    </div>
                    {/* Chart area */}
                    <div className="flex-1 bg-[#1f2937] rounded p-2 flex items-end gap-1 overflow-hidden">
                      {[40,65,48,80,55,90,72,85,60,95,70,88].map((h, i) => (
                        <div key={i} className="flex-1 flex flex-col justify-end">
                          <div
                            className="rounded-sm bg-primary/70"
                            style={{ height: `${h}%`, animationDelay: `${i * 0.06}s` }}
                          />
                        </div>
                      ))}
                    </div>
                    {/* Table rows */}
                    <div className="bg-[#1f2937] rounded p-2 space-y-1">
                      {["Nike Summer '26","Apple AirPods Pro","Tesla Model Y"].map((name, i) => (
                        <div key={name} className="flex items-center justify-between">
                          <span className="text-xs font-mono text-gray-300 truncate">{name}</span>
                          <span className="text-xs font-mono text-green-400 ml-2">+{[12,8,23][i]}%</span>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              )}

              {/* Build complete overlay */}
              {showBadge && (
                <div className="border-t border-green-500/30 bg-green-500/5 px-4 py-2.5 flex items-center gap-2">
                  <Rocket className="w-4 h-4 text-green-400" />
                  <span className="text-xs font-mono text-green-400 font-bold">Build complete — app deployed in 47 seconds</span>
                </div>
              )}
            </div>
          </div>

          {/* Replay indicator */}
          <div className="flex items-center justify-center mt-4 gap-2">
            {[0,1,2,3,4].map(i => (
              <span
                key={i}
                className={`block w-1.5 h-1.5 rounded-full transition-all duration-300 ${i === Math.min(phase, 4) ? "bg-primary w-6" : "bg-border"}`}
              />
            ))}
            <span className="text-xs font-mono text-muted-foreground/40 ml-2">auto-playing demo</span>
          </div>
        </div>

        {/* CTA */}
        <div className="text-center mt-16">
          <div className="inline-flex flex-col items-center gap-4">
            <p className="text-lg font-mono text-muted-foreground">
              Your first 3 builds are <span className="text-primary font-bold">completely free.</span> No credit card required.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link href="/register">
                <button className="flex items-center gap-2 px-8 py-4 bg-primary text-primary-foreground font-display font-bold text-lg rounded hover:opacity-90 transition-all glow-primary-hover cyber-clip">
                  <Zap className="w-5 h-5" />
                  TRY IT FREE — START BUILDING NOW
                </button>
              </Link>
              <Link href="/pricing">
                <button className="flex items-center gap-2 px-8 py-4 border border-border text-muted-foreground font-mono text-sm rounded hover:border-primary hover:text-primary transition-all">
                  See Pricing Plans
                </button>
              </Link>
            </div>
            <p className="text-xs font-mono text-muted-foreground/50">
              Free plan · No setup · Apps live in seconds
            </p>
          </div>
        </div>

      </div>
    </section>
  );
}
